import fs from 'node:fs/promises';
import path from 'node:path';
import * as XLSX from 'xlsx';

const OUT_DIR = 'data';
const OUT_JSON = path.join(OUT_DIR, 'seguros-vehiculares.json');
const OUT_META = path.join(OUT_DIR, 'seguros-vehiculares-meta.json');

const SHARE_ID = process.env.FIAS_SEGUROS_SHARE_ID || '';
const SHARE_LINK = process.env.FIAS_SEGUROS_EXCEL_URL || '';
const DOWNLOAD_CANDIDATES = [
  SHARE_LINK && { name: 'Share link con download=1', url: SHARE_LINK.includes('?') ? `${SHARE_LINK}&download=1` : `${SHARE_LINK}?download=1` },
  SHARE_LINK && { name: 'Share link con web=0 y download=1', url: SHARE_LINK.includes('?') ? `${SHARE_LINK}&web=0&download=1` : `${SHARE_LINK}?web=0&download=1` },
  SHARE_ID && { name: 'SharePoint download.aspx con share id', url: `https://fiasec-my.sharepoint.com/personal/jcruzg_fias_org_ec/_layouts/15/download.aspx?share=${SHARE_ID}` }
].filter(Boolean);

const FIELD_ALIASES = {
  nro:['nro','nro.','no','numero','número','id'],
  programa:['programa','proyecto','reserva','reserva / proyecto','reserva proyecto','fondo / programa / proyecto','ubicacion','ubicación'],
  placa:['placa','placas'], categoria:['categoria','categoría','tipo','clase'], marca:['marca'], modelo:['modelo'], anio:['año','anio','ano','year'], color:['color'],
  poliza:['poliza','póliza','id_poliza','poliza id','póliza id'], polizaNumero:['poliza numero','póliza número','numero poliza','número póliza'], aseguradora:['aseguradora','compañia','compania','compañía'],
  vigDesde:['vigencia desde','vig desde','desde','vig_desde'], vigHasta:['vigencia hasta','vig hasta','hasta','vig_hasta'], estado:['estado','estado póliza','estado poliza'], diasRestantes:['dias restantes','días restantes'],
  valorAsegurado:['valor asegurado'], valorAccesorios:['valor accesorios','accesorios'], totalAsegurado:['total asegurado','suma asegurada','valor total asegurado'], totalPagado:['total pagado','prima total','total'],
  deducible:['deducible','deducibles'], asistencia:['asistencia','telefono asistencia','teléfono asistencia','contacto asistencia'], responsable:['responsable','custodio','responsable custodio'], expediente:['expediente','link','enlace','pdf','documento respaldo'], observaciones:['observaciones','alertas'], mostrarWeb:['mostrar web','mostrar_web','publicar','visible']
};
const normalizeText = v => String(v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const normalizeKey = v => normalizeText(v).replace(/[%()$]/g,'').replace(/[^a-z0-9]+/g,'');
const NORMALIZED_ALIASES = Object.fromEntries(Object.entries(FIELD_ALIASES).map(([k,a])=>[k,a.map(normalizeKey)]));
function valueByAliases(row, field){for(const [key,value] of Object.entries(row)){if((NORMALIZED_ALIASES[field]||[]).includes(normalizeKey(key))) return value;} return '';}
function parseNumber(value){if(value===null||value===undefined||value==='') return 0; if(typeof value==='number') return value; let s=String(value).trim().replace(/[^\d,.-]/g,''); if(s.includes(',')&&s.includes('.')) s=s.replace(/\./g,'').replace(',','.'); else if(s.includes(',')) s=s.replace(',','.'); const n=Number(s); return Number.isFinite(n)?n:0;}
function excelDateToISO(value){if(!value) return ''; if(value instanceof Date&&!Number.isNaN(value.getTime())) return value.toISOString().slice(0,10); if(typeof value==='number'){const p=XLSX.SSF.parse_date_code(value); if(!p) return ''; return `${String(p.y).padStart(4,'0')}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`;} const t=String(value).trim(); const iso=t.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/); if(iso){const[,y,m,d]=iso;return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;} const lat=t.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})/); if(lat){const[,d,m,y]=lat;return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;} return t;}
function daysLeft(dateText){if(!dateText) return ''; const end=new Date(`${dateText}T12:00:00-05:00`); if(Number.isNaN(end.getTime())) return ''; const now=new Date(); return Math.ceil((end-now)/(1000*60*60*24));}
function stateFromDate(vigHasta, estadoManual){if(estadoManual) return String(estadoManual).trim(); const d=daysLeft(vigHasta); if(d==='') return ''; if(d<0) return 'VENCIDA'; if(d<=30) return 'POR VENCER'; return 'VIGENTE';}
function normalizeImported(row,index){const vigHasta=excelDateToISO(valueByAliases(row,'vigHasta')); const estado=stateFromDate(vigHasta,valueByAliases(row,'estado')); return {nro:valueByAliases(row,'nro')||index+1, programa:String(valueByAliases(row,'programa')??'').trim(), placa:String(valueByAliases(row,'placa')??'').trim(), categoria:String(valueByAliases(row,'categoria')??'').trim(), marca:String(valueByAliases(row,'marca')??'').trim(), modelo:String(valueByAliases(row,'modelo')??'').trim(), anio:parseNumber(valueByAliases(row,'anio'))||'', color:String(valueByAliases(row,'color')??'').trim(), poliza:String(valueByAliases(row,'poliza')??'').trim(), polizaNumero:String(valueByAliases(row,'polizaNumero')??'').trim(), aseguradora:String(valueByAliases(row,'aseguradora')??'').trim(), vigDesde:excelDateToISO(valueByAliases(row,'vigDesde')), vigHasta, estado, diasRestantes:daysLeft(vigHasta), valorAsegurado:parseNumber(valueByAliases(row,'valorAsegurado')), valorAccesorios:parseNumber(valueByAliases(row,'valorAccesorios')), totalAsegurado:parseNumber(valueByAliases(row,'totalAsegurado')), totalPagado:parseNumber(valueByAliases(row,'totalPagado')), deducible:String(valueByAliases(row,'deducible')??'').trim(), asistencia:String(valueByAliases(row,'asistencia')||'099 555 3333').trim(), responsable:String(valueByAliases(row,'responsable')??'').trim(), expediente:String(valueByAliases(row,'expediente')??'').trim(), observaciones:String(valueByAliases(row,'observaciones')??'').trim(), mostrarWeb:String(valueByAliases(row,'mostrarWeb')||'SI').trim()};}
function isProbablyHtml(buffer){const s=buffer.subarray(0,700).toString('utf8').trim().toLowerCase(); return s.startsWith('<!doctype html')||s.startsWith('<html')||s.includes('<html')||(s.includes('microsoft')&&s.includes('sharepoint'));}
function isProbablyXlsx(buffer){return buffer.length>4&&buffer[0]===0x50&&buffer[1]===0x4b;}
async function downloadExcel(){if(!DOWNLOAD_CANDIDATES.length) throw new Error('Configura FIAS_SEGUROS_EXCEL_URL o FIAS_SEGUROS_SHARE_ID en GitHub Actions.'); const errors=[]; for(const c of DOWNLOAD_CANDIDATES){console.log(`Intentando descarga: ${c.name}`); try{const res=await fetch(c.url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 GitHubActions FIAS Seguros','Accept':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/octet-stream,*/*'}}); const ab=await res.arrayBuffer(); const buffer=Buffer.from(ab); const contentType=res.headers.get('content-type')||'sin content-type'; console.log(`HTTP ${res.status}; ${contentType}; bytes ${buffer.length}`); if(!res.ok){errors.push(`${c.name}: HTTP ${res.status}`); continue;} if(buffer.length<1000||isProbablyHtml(buffer)||contentType.toLowerCase().includes('text/html')){errors.push(`${c.name}: SharePoint devolvió HTML o respuesta inválida.`); continue;} if(!isProbablyXlsx(buffer)){errors.push(`${c.name}: respuesta no parece XLSX.`); continue;} return {buffer, sourceName:c.name, sourceUrl:c.url, contentType, bytes:buffer.length};}catch(e){errors.push(`${c.name}: ${e.message}`)}} throw new Error('No se pudo descargar XLSX válido.\n'+errors.map((e,i)=>`${i+1}. ${e}`).join('\n'));}
function findHeaderRow(matrix){return matrix.findIndex(row=>Array.isArray(row)&&row.some(c=>['nro','nro.','placa','placas'].includes(normalizeText(c)))&&row.some(c=>normalizeText(c).includes('poliza')||normalizeText(c).includes('póliza')));}
function rowsFromWorkbook(workbook){let selected=null; for(const sheetName of workbook.SheetNames){const sheet=workbook.Sheets[sheetName]; const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:null}); const headerIndex=findHeaderRow(matrix); console.log(`Hoja "${sheetName}": filas ${matrix.length}; encabezado ${headerIndex}`); if(headerIndex>=0){selected={sheetName,matrix,headerIndex}; break;}} if(!selected) throw new Error('No se encontró una fila de encabezados con Placa y Póliza.'); const headers=selected.matrix[selected.headerIndex].map(h=>String(h??'').trim()); const rows=selected.matrix.slice(selected.headerIndex+1).filter(r=>Array.isArray(r)&&r.some(c=>c!==null&&c!==undefined&&String(c).trim()!=='')).filter(r=>String(r[0]??'').trim().toLowerCase()!=='total general').map((r,i)=>{const obj={}; headers.forEach((h,j)=>{if(h)obj[h]=r[j]}); return normalizeImported(obj,i);}).filter(r=>r.placa||r.poliza||r.marca||r.modelo); return {rows,sheetName:selected.sheetName,headerIndex:selected.headerIndex,headers};}
async function main(){await fs.mkdir(OUT_DIR,{recursive:true}); const dl=await downloadExcel(); const wb=XLSX.read(dl.buffer,{type:'buffer',cellDates:true}); const parsed=rowsFromWorkbook(wb); if(!parsed.rows.length) throw new Error('No se generaron registros válidos.'); const meta={generatedAt:new Date().toISOString(),records:parsed.rows.length,sheetName:parsed.sheetName,headerRowIndex:parsed.headerIndex,headers:parsed.headers,sourceName:dl.sourceName,sourceUrl:dl.sourceUrl,contentType:dl.contentType,bytes:dl.bytes}; await fs.writeFile(OUT_JSON,JSON.stringify(parsed.rows,null,2),'utf8'); await fs.writeFile(OUT_META,JSON.stringify(meta,null,2),'utf8'); console.log(`JSON generado: ${OUT_JSON}; registros ${parsed.rows.length}`);}
main().catch(err=>{console.error('Error generando data/seguros-vehiculares.json'); console.error(err); process.exit(1);});
